<a href="https://colab.research.google.com/github/ShreyaaChauhan/Deep_Learning_with_Pytorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.12.1+cu113


# Introduction to Tensors



### Creating tensors

In [2]:
#scalar
scalar = torch.tensor(7)
scalar.ndim


0

In [3]:
#Get tensor back as Python int
scalar.item()

7

In [10]:
#vector
vector = torch.tensor([7,7,5])
print(vector.ndim)
print(vector.shape)

1
torch.Size([3])


In [18]:
matrix = torch.tensor([[7,8], [9,10]])

In [31]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3,4],[3,4,5,4],[5,6,7,4]], [[1,2,3,4],[3,4,5,4],[5,6,7,4]]])

In [32]:
TENSOR.shape

torch.Size([2, 3, 4])

### Random Tensors

Why random tensors?
Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data



```
start with random numbers -> look at the data -> update random numbers -> look aat data -> update random numbers
```



In [37]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.5059, 0.1252, 0.4201, 0.6343],
        [0.9600, 0.6875, 0.3286, 0.8328],
        [0.1836, 0.2158, 0.5537, 0.2181]])

In [39]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (244,244,3)) # height, width, channels (RGB)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([244, 244, 3]), 3)

### Zeros and ones

In [40]:
# Create a tensor of all zeros
zeros = torch.zeros(size = (3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [46]:

# Create a tensor of all ones
ones = torch.ones(size=(3,4), dtype = torch.float64)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)

### Creating a range of tensors and tensors-like

In [58]:
zero_to_six = torch.arange(0,8,2)
zero_to_six


tensor([0, 2, 4, 6])

In [60]:
# creating tensors like
zero_to_six_zeros = torch.zeros_like(input = zero_to_six)
zero_to_six_zeros

tensor([0, 0, 0, 0])

### Tensor Datatypes






**Note**: Tensor datatypes is one of the 3 big errors we'll run into with Pytorch & deep learning:

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device


Important datatypes while creating tensors 

dtype, device, require_grad 

In [67]:
float_32_tensor = torch.tensor([3.0,6.0,9.0], 
                               dtype = None, # what datatype is the tensor (e.g. float32 pr float16)
                               device = "cpu", # what device is your tensor on
                               requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor.dtype

torch.float32

In [68]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

### Getting information from tensors



1. Tensors not right datatype - TODO tensor.dtype
2. Tensors not right shape - TODO tensor.shape
3. Tensors not on the right device - TODO tensor.device

In [69]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.5367, 0.2325, 0.6231, 0.5301],
        [0.2497, 0.1363, 0.8128, 0.6185],
        [0.3857, 0.2311, 0.6546, 0.7081]])

In [70]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor:{some_tensor.dtype}")
print(f"Shape of tensor:{some_tensor.shape}")
print(f"Device tensor is on:{some_tensor.device}")

tensor([[0.5367, 0.2325, 0.6231, 0.5301],
        [0.2497, 0.1363, 0.8128, 0.6185],
        [0.3857, 0.2311, 0.6546, 0.7081]])
Datatype of tensor:torch.float32
Shape of tensor:torch.Size([3, 4])
Device tensor is on:cpu


### Manipulating tensors (tensor operations)

Tensor operations includes:

Tensor operations include:
* Addition
* Subtraction
* Multiplication
* Division
* Matrix Multiplication



In [74]:
# Create a tensor
tensor = torch.tensor([1,2,3])
tensor +10

tensor([11, 12, 13])

In [75]:
# Multiply tensor by 10 
tensor *10

tensor([10, 20, 30])

In [76]:
# Subtstract 10
tensor -10

tensor([-9, -8, -7])

In [77]:
# Ty out Pytorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [78]:
torch.add(tensor , 10)

tensor([11, 12, 13])

### Matrix Multiplication


Two main ways of performing multiplication in neural networks and deep learning

1. Element-wise multiplication

2. Matrix multiplication 

There are two main rules that performing matrix multiplication need to satisfy : 

1. The **inner dimensions** must match:
- (3,2) @ (3,2) won't work
- (2,3) @ (3,2) will work
2. The resulting matrix has the shape of the **outer dimensions**:
- (2,3) @ (3,2) -> (2,2)
- (3,2) @ (2,3) -> (3,3)

In [79]:
# Element wise multiplication 
print(tensor , "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [80]:
# matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

1 To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**

In [83]:
tensor_A = torch.tensor([[1,2],[3,4],[5,6]])
tensor_B = torch.tensor([[7,10],[8,11],[9,12]])
torch.mm(tensor_A.T, tensor_B)

tensor([[ 76, 103],
        [100, 136]])

In [86]:
tensor_A.T

tensor([[1, 3, 5],
        [2, 4, 6]])

### Finding the min, max, mean, sum etc (tensor aggregation)

In [90]:
# Create a tensor 
x = torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [89]:
# Find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [91]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()


(tensor(46.), tensor(46.))

In [92]:
# Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

### Finding the positional min and max

In [93]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [95]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position of target tensor where the minimun value occurs
x.argmin()

tensor(0)

In [97]:
x.argmax()

tensor(9)

### Reshaping, stacking, sqeezing and unsqueezing *tensors*

* Reshaping - reshape an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory
* Stacking - combine multiple tensors on top of each other (vstaack) or side by side (hstack)
* Sqeeze - remove att `1` dimensions from a tensor
* Unsqeeze - add a `1` dimesion to a target tensor
* Permute - Rteurn a view of the input with dimensions permuted (swapped) in a ertain way

In [108]:
# Let's create a tensor
x = torch.arange(1,10)
x.shape

torch.Size([9])

In [110]:
# Add an extra dimension
x_reshaped = x.reshape(3,3)
x_reshaped

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [113]:
# Change the view
z = x.view(1,9)
z, z.shape
# Note :- Changing z changes x (because a view of a tensor shares the same memory as the original tensor)

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [116]:
# Stack tensor on top of each other
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [117]:
#torch.squeeze() - removes all single dimensions from a target tensor
x_reshaped

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [121]:
x_stacked.squeeze()

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [123]:
# torch.permute - rearranges the dimensions of a target tensor in a specifies order
x_original = torch.rand(224,224,3)

#Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2,0,1) # shifts axis 0->1 , 1->2, 2->0

print(f"Previous shape : {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape : torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


### Indexing (selecting data from tensors)

In [126]:
x = torch.arange(1,10). reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [129]:
#Let's index on our new tensor
x[0][0][0]


tensor(1)

### Pytorch tensors & Numpy


Numpy is a popular scientific python numerical computing libraru and because of this, Pytorch has functionality to interact with it. 

- Data in Numpy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
- Pytorch tensor -> numpy -> `torch.Tensor.numpy()`

### Reproducbility (trying to take random out of random)



To reduce the randomness in neural networks and Pytorch comes the concept of a **random seed** Essentially what the random seed does is "flavour" the randomness.

In [131]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
print(random_tensor_A ==  random_tensor_B)

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [137]:
#Set the random seed
RANDOM_SEED = 100
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)
print(random_tensor_C)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.1117, 0.8158, 0.2626, 0.4839],
        [0.6765, 0.7539, 0.2627, 0.0428],
        [0.2080, 0.1180, 0.1217, 0.7356]])
tensor([[0.1117, 0.8158, 0.2626, 0.4839],
        [0.6765, 0.7539, 0.2627, 0.0428],
        [0.2080, 0.1180, 0.1217, 0.7356]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and Pytorch objects on the GPUs (and making faster computations)

GPUs = faster computations on numbers, thanks to CUDA + NVIDIA hardware pytorch behind the scenes to make this possible


### 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU (options to upgrade as well)
2. Use your own GPU - takes little bit of setup and requires the investment of purchsing a GPU
3. Use cloud computing - GCP, AWS, Aure, these services allow us to rent computers on the cloud and access them

In [1]:
!nvidia-smi

Mon Oct 24 22:37:59 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   43C    P8     9W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

### Check for GPU access with pytorch

In [2]:
# Check for GPU with Pytorch
import torch
torch.cuda.is_available()

True

For Pytorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code
E.G run on GPU if available, else default to CPU

In [4]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [5]:
# Count number of devices
torch.cuda.device_count()

1

### Putting tensors (and models) on the DPU
The reason we want our tensors/models on the GPU is because using GPU results in faster computations.  

In [6]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1,2,3])
tensor.device

device(type='cpu')

In [7]:
#Mve tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu.device

device(type='cuda', index=0)

### Moving tensors back to the CPU

In [8]:
# of tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: ignored

In [13]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])