<a href="https://colab.research.google.com/github/ShreyaaChauhan/Deep_Learning_with_Pytorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.12.1+cu113


# Introduction to Tensors



### Creating tensors

In [2]:
#scalar
scalar = torch.tensor(7)
scalar.ndim


0

In [3]:
#Get tensor back as Python int
scalar.item()

7

In [10]:
#vector
vector = torch.tensor([7,7,5])
print(vector.ndim)
print(vector.shape)

1
torch.Size([3])


In [18]:
matrix = torch.tensor([[7,8], [9,10]])

In [31]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3,4],[3,4,5,4],[5,6,7,4]], [[1,2,3,4],[3,4,5,4],[5,6,7,4]]])

In [32]:
TENSOR.shape

torch.Size([2, 3, 4])

### Random Tensors

Why random tensors?
Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data



```
start with random numbers -> look at the data -> update random numbers -> look aat data -> update random numbers
```



In [37]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.5059, 0.1252, 0.4201, 0.6343],
        [0.9600, 0.6875, 0.3286, 0.8328],
        [0.1836, 0.2158, 0.5537, 0.2181]])

In [39]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (244,244,3)) # height, width, channels (RGB)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([244, 244, 3]), 3)

### Zeros and ones

In [40]:
# Create a tensor of all zeros
zeros = torch.zeros(size = (3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [46]:

# Create a tensor of all ones
ones = torch.ones(size=(3,4), dtype = torch.float64)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)

### Creating a range of tensors and tensors-like

In [58]:
zero_to_six = torch.arange(0,8,2)
zero_to_six


tensor([0, 2, 4, 6])

In [60]:
# creating tensors like
zero_to_six_zeros = torch.zeros_like(input = zero_to_six)
zero_to_six_zeros

tensor([0, 0, 0, 0])

### Tensor Datatypes






**Note**: Tensor datatypes is one of the 3 big errors we'll run into with Pytorch & deep learning:

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device


Important datatypes while creating tensors 

dtype, device, require_grad 

In [67]:
float_32_tensor = torch.tensor([3.0,6.0,9.0], 
                               dtype = None, # what datatype is the tensor (e.g. float32 pr float16)
                               device = "cpu", # what device is your tensor on
                               requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor.dtype

torch.float32

In [68]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

### Getting information from tensors



1. Tensors not right datatype - TODO tensor.dtype
2. Tensors not right shape - TODO tensor.shape
3. Tensors not on the right device - TODO tensor.device

In [69]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.5367, 0.2325, 0.6231, 0.5301],
        [0.2497, 0.1363, 0.8128, 0.6185],
        [0.3857, 0.2311, 0.6546, 0.7081]])

In [70]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor:{some_tensor.dtype}")
print(f"Shape of tensor:{some_tensor.shape}")
print(f"Device tensor is on:{some_tensor.device}")

tensor([[0.5367, 0.2325, 0.6231, 0.5301],
        [0.2497, 0.1363, 0.8128, 0.6185],
        [0.3857, 0.2311, 0.6546, 0.7081]])
Datatype of tensor:torch.float32
Shape of tensor:torch.Size([3, 4])
Device tensor is on:cpu


### Manipulating tensors (tensor operations)

Tensor operations includes:

Tensor operations include:
* Addition
* Subtraction
* Multiplication
* Division
* Matrix Multiplication



In [74]:
# Create a tensor
tensor = torch.tensor([1,2,3])
tensor +10

tensor([11, 12, 13])

In [75]:
# Multiply tensor by 10 
tensor *10

tensor([10, 20, 30])

In [76]:
# Subtstract 10
tensor -10

tensor([-9, -8, -7])

In [77]:
# Ty out Pytorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [78]:
torch.add(tensor , 10)

tensor([11, 12, 13])

### Matrix Multiplication


Two main ways of performing multiplication in neural networks and deep learning

1. Element-wise multiplication

2. Matrix multiplication 

In [79]:
# Element wise multiplication 
print(tensor , "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [80]:
# matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)